### PR TITLE
Simulation

### PR DESCRIPTION
**Pull request by rongxinyin**
Add simulation scripts and test example files. Need to link the front end simulation function to call pov_test python script.

### CODE REVIEW

**Comment by rongxinyin** [comment]
Add test files and it works.

**Comment by leongmichael** [comment]
TODO: functionality with simulation page

**Comment by rongxinyin** [comment]
@leongmichael use main.py for calling simulator on the simulation page.

**Comment by leongmichael** [comment]
Michael TODO:

- [x] update sim site input
- [x] update main.py command line input (use terminal args) 
- [x] configure backend server call
- [x] add bldng9 for commute info 
- [x] loading progress bar 
- [x] download the final result

**Review by leongmichael — APPROVED** [review]
LGTM

**Pull request merged**
